<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>c</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)
		 /\*\*(?!\*)
		|^(?![^{]*?//|[^{]*?/\*(?!.*?\*/.*?\{)).*?\{\s*($|//|/\*(?!.*?\*/.*\S))
	</string>
	<key>foldingStopMarker</key>
	<string>(?&lt;!\*)\*\*/|^\s*\}</string>
	<key>keyEquivalent</key>
	<string>^~C</string>
	<key>name</key>
	<string>C (Ruby)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(rb_[a-z_]*)\b</string>
			<key>name</key>
			<string>support.function.ruby.c</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(VALUE)\b</string>
			<key>name</key>
			<string>storage.type.ruby.c</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>common C constant naming idiom -- rb_cConstantVariable</string>
			<key>match</key>
			<string>\brb_c[A-Z]\w*\b</string>
			<key>name</key>
			<string>constant.other.variable.ruby.c</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.c</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.c.ruby</string>
	<key>uuid</key>
	<string>A6C5F464-C4A4-4C94-A8DC-E442FFBD823D</string>
</dict>
</plist>
